# Generated by Django 4.1.3 on 2022-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=25)),
            ],
        ),
    ]
