# Generated by Django 4.1.3 on 2022-12-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('eMail', models.EmailField(max_length=254)),
                ('passWord', models.CharField(max_length=14)),
            ],
        ),
    ]
